### ISSUE TITLE
Ideas for cache checksum verification

### ISSUE THREAD

**Issue by mmccarty** [ContinuumIO/intake#152]
> A method to determine updates for remote data files need to be explored so that cached data can be refreshed regardless of expiration. Checksum verification is problematic since that would require downloading remote files with each check, which defeats the purpose of caching in the first place.

From @jbednar: Can you use modified date and size as an approximation to a checksum? Seems like that information will sometimes be available, and could be used if it is.

**Comment by mmccarty** [comment]
That would require the remote data source to return the file size, which they don't always do.

**Comment by philippjfr** [comment]
Just speculating here but couldn't you put a checksum in the catalog entry which intake would then compare against on loading?

**Comment by martindurant** [comment]
Sorry didn't follow: we download a file to the cache, then calculate its checksum? How does that guard against corruption? Or are you thinking that there may be a possibility of the file changing in-situ in the cache directory?

**Comment by jbednar** [comment]
I don't think we need to worry much about the file changing in-situ, but I do think it's crucial to do something about incomplete downloads.  I haven't tried to look at the code involved, so I don't know how precisely it happens, but I've had an intake cache get filled with an unusable file where the easiest solution was simply to delete the cache and let everything download again.  My guess is that due to internet connectivity or other similar issues, the download was stalled and I ended up killing the notebook or process involved and starting over, leaving a partial file that caused problems the next time.  Philipp's proposed solution would guard against this without slowing down repeated accesses by only generating the checksum file when the file is first used.

If the main worry (which I think is true) is incomplete rather than corrupted downloads, a simpler solution would be to simply download to a different filename (like Chrome's ".... .crdownload" files) until the download is complete), renaming it to the final name in an atomic action at the end.  That might be sufficient and wouldn't require computing or storing checksums.

**Comment by philippjfr** [comment]
I do agree a partial download might be the main worry, so having a temporary file name seems like a better solution.

**Comment by martindurant** [comment]
Ah, OK, that does make sense.
