### ISSUE TITLE
Plugin name collisions

### ISSUE THREAD

**Issue by jacobtomlinson** [ContinuumIO/intake#161]
First off thanks so much for your awesome work on Intake!

Today I've been developing an [Intake Plugin for Iris](https://github.com/informatics-lab/intake-iris) and noticed that if I create a `netcdf` plugin it collides with the xarray plugin and Intake only loads one of them at import time. 

<img width="844" alt="image" src="https://user-images.githubusercontent.com/1610850/45559064-627ff600-b839-11e8-93e8-0118c5e68734.png">

Luckily for my testing iris comes before xarray alphabetically so I have been able to test my plugin without removing the xarray one. 

Given that both iris and xarray can open netcdf datasets I think this choice should probably be down to the user as to which one they want it to be loaded with. It would be great to update intake to be able to load multiple plugins for the same datatype and then allow the user to pass a kwarg somewhere to specify which one they want to use at a particular moment.

**Comment by martindurant** [comment]
Can you check please, does supplying the plugin explicitly in the catalogue (see [here](https://intake.readthedocs.io/en/latest/catalog.html#extra-plugins)) fix the choice? An obvious solution would be to name your plugin something more specific like iris-netcdf, but I can see why you wouldn't want to do that. A config system "preferred plugins" is tractable, but I wonder whether this would confuse people. 

Is this intake-iris available? It could be mentioned on https://intake.readthedocs.io/en/latest/plugin-directory.html .

**Comment by seibert** [comment]
The intent was that plugins were not 1-to-1 mapped to file formats, because there may be different ways to load a given file.  For example, I had imagined that there would be an `hdf5_table` and `hdf5_array` that both read HDF5 files, but return the data as a dataframe or an array, respectively.

In the above case, if they plugins have separate names, then the user makes the choice that way, rather than a kwarg to an aliased meta-plugin.

**Comment by jacobtomlinson** [comment]
@martindurant @seibert thanks for the prompt responses!

I agree that 1-to-1 mappings may not be ideal, I was working from a fork of `intake-xarray` which uses the `netcdf` plugin name. My concern is that a data provider (us at the Met Office for example) may package some netcdf data as an intake manifest. Our internal users will want that to load with iris, however if we are sharing externally some people may prefer xarray.

I'm trying to think about the workflow of `intake.cat.<dataset>.read()`. How can the user specify what they want while keeping the catalog generic?

**Comment by jacobtomlinson** [comment]
Also yes @martindurant it is public, its very rough but happy for it to be listed!

**Comment by martindurant** [comment]
Having a catalogue with a source of type "netcdf" where the user gets to decide at load time which plugin to use sounds problematic, since different plugins will in general need different arguments, even for the same underlying data format. That also nixes the "preferred" plugins idea I mentioned above. The only thing that I could think of to really solve this:
- have strong wording that ew plugins should have unique names compared to the already-known plugins (which will annoy people who feel their plugin better matches a particular format "name"): this is the case in pypi/conda, but of course there there is a real central registry. It would presumably end up with longer names generally.
- be able to specify the plugin by `package.module.Class` right in data source spec block. This could have a positive side effect of informative "can't load this, you need to install 'package'" messages, but obviously makes catalogues uglier.

**Comment by jacobtomlinson** [comment]
Its definitely a tricky situation. I strongly feel that data providers shouldn't make decisions about the tools that data consumers will use. However from a technical viewpoint I understand that the data providers may need to include some tool specific configuration in the manifest in order for it to load correctly.

> which will annoy people who feel their plugin better matches a particular format "name"

The whole idea of a land grab for plugin to file type mappings concerns me a lot. It's not really about which tool is better. Any tool that has a community should be able to have that tool represented as a plugin. If there are multiple tools which can open the same file type in a very similar way then they should be able to open any dataset of that type. Off the top of my head for `netcdf` I can think of `netcdf4-python`, `xarray`, `iris` and `metpy`. Users from all of these communities may want to open a dataset that we publish from the Met Office, and why should we limit them to `iris` only?

I think I prefer your second option. Perhaps as a middle ground solution there is a way where the data provider could specify multiple plugins and their configuration which would allow users to select the driver from some predefined ones. Perhaps something like:

```yaml
    urlpath: '/path/to/come/file.nc'
    driver: 
      - name: netcdf-xarray
        args:
          some: 'args for xarray'
      - name: netcdf-iris
        args:
          some: 'args for iris'
```

That way at least some of the tools could be supported out of the box. And hopefully if the provider is being open then people from communities that are not represented could PR driver info for the tool of their choice into the dataset.

**Comment by martindurant** [comment]
OK, we have come up with a number of possible solutions, which I will list here, from simplest to more complex. @jacobtomlinson , it would be great to hear your views, and those of any others who are thinking of using Intake. Compatibility with existing Intake catalogues would be nice, but we are still early enough that we could choose to break.

1) demand specific, unique plugin names. There is currently no restriction on what to call a plugin, and the names are referenced as-is. We could rename existing plugins to be more specific.

2) allow specification of plugin using fully-qualified syntax, like `package.module.Plugin`. This is a particular flavour of 1); another possibility here would be plugin=, package=, i.e., add another (optional) parameter to a spec

3) allow for multiple, well-specified plugins to apply to a single data source. In this case, there are global arguments used for all plugins, but we may want to provide a nested way to also give arguments to each of the plugins

```
mydata:
  driver:
    intake_iris.netcdf:
       args:
         extra: True
    intake_xarray.netcdf: {}
  args:
    urlpath: gcs://blah
    storage_options: {}
```
(or we could allow a string or list-of-strings to driver, and have the specific arguments elsewhere)
Here, in the case that the driver were simply 'netcdf', Intake would be free to choose any plugin with that name, as happens now.

4) Some config system to be able to specify globally or at runtime that "netcdf" refers to `intake_iris.NetCDFSource`. This is not very flexible and would require writing data source specs that can work with any possible preference

5) Intra-catalogue aliases, so that the specs for loading some data with iris versus loading with xarray stay separate, but a single meta-source refers to them

```
data_iris_version:
  driver: intake_iris.netcdf
  args: ...
data_xarray_version:
  driver: intake_xarray.netcdf
  args: ...
data:
  driver: alias
  sources:
    iris: data_iris_version
    xarray: data_xarray_version
  default: iris
```
such that `cat.data("iris") == cat.data_iris_version()`. Perhaps this alias could be generated in a simpler way; perhaps it could hold common arguments or metadata for both entries.

**Comment by jacobtomlinson** [comment]
I feel like 1, 2 and 3 are not mutually exclusive. We could do something which is a combination of all of them. I also find 5 intriguing.

As you say perhaps it would be useful at this point to get some more opinions on this. I'm going to invoke some names of people who I've discussed this topic with at some point recently. To those of you I'm name dropping I would appreciate if you could have a read of this thread and add your thoughts. @niallrobinson, @pelson, @dkillick, @mrocklin, @dopplershift, @jhamman, @rsignell.

**Comment by niallrobinson** [comment]
My feeling is that it would be a design mistake for Intake to be opinionated about how people should be accessing datasets. Making plugins which necessitate the naming convention <analysis_tool>-<dataset> name, e.g. `iris-netcdf`, is not good separation of concerns.

From a design point of view, it seems that having a model where the manifest can specify multiple plugins, with a default plugin but the choice of using other plugins, could be the way to go.

**Comment by martindurant** [comment]
#163 is now ready, please review if you have time.

**Comment by jacobtomlinson** [comment]
Thanks @martindurant for your hard work enabling this.

**Comment by jacobtomlinson** [comment]
We've just written `intake-s3-manifests` and I'm part way through `intake-dynamodb` too!

**Comment by martindurant** [comment]
Feel free to add PRs to change https://intake.readthedocs.io/en/latest/plugin-directory.html as you bring them up.
Also, your install instructions probably also need `-c intake`, at least until intake packages migrate to conda-forge and/or main.
