### ISSUE TITLE
advice on data hierarchies

### ISSUE THREAD

**Issue by niallrobinson** [ContinuumIO/intake#177]
Hi everyone. I'm new here, but I work with @jacobtomlinson who's been putting some PRs in lately.

Has anyone got any thoughts about how we could group objects a little? For instance, I am trying to make available various data which represents [Typhoon Koppu](https://en.wikipedia.org/wiki/Typhoon_Koppu), including rainfall, wind speed, etc etc. All of these are separate data objects, and currently, intake would represent them as such inside a catalogue. However, I feel like it would be good to be able to group them together somehow, otherwise, we're getting into the dodgy territory of naming conventions like `intake.catalogue.typhoon_koppu_rainfall` etc.

Is there any appetite for hierarchies? I guess in the catalogues. I think ideally I'd like to be able to do `intake.catalogue.typhoon_koppu.rainfall`. And if we're going there, should I then be able to do `intake.catalogue.case_studies.typhoon_koppu.rainfall`.

I'm a bit conflicted about this stuff - on the one hand too much hierarchy means that stuff can get buried. But then without some kind of hierarchy, it'll just be anarchy.

If hierarchies of catalogues sounds like a good idea then point me in the right direction for a PR 😄

**Comment by martindurant** [comment]
You can do this already: the two data sources intake.catalog.local.YAMLFileCatalog (yaml_file_cat) and YAMLFilesCatalog (yaml_files_cat) enable you to have an entry in a cat which is itself a cat; the two cases are for a specific file, and all files in a directory, respectively.
A simplistic example is in [the tests](https://github.com/ContinuumIO/intake/blob/master/intake/catalog/tests/catalog1.yml#L12), note `driver: yaml_file_cat`. This is a contrived case, since the entry actually refers back to the same catalog, so you get recursion. Therefore, you can do
```
cat = intake.open_catalog('.../catalog1.yaml')
cat.nested.nested.entry1
```

You can also, if you wish, create new "catalog" type plugins (typically deriving from Catalog) which are able to generate entries from some other prescription or by querying some external data provider. This is what is done in [SQLCatalog](https://github.com/ContinuumIO/intake-sql/blob/master/intake_sql/sql_cat.py#L7), which generates an entry for each table reported by the database server.

If you can think of a way to express all of this in the documentation, would be glad to see it!

**Comment by niallrobinson** [comment]
Oooh that's useful - thanks for the tip. I'll try and do it before trying to write some docs!
