### ISSUE TITLE
Support for caching of data files

### ISSUE THREAD

**Issue by seibert** [ContinuumIO/intake#84]
A commonly request use case for an Intake catalog is a hybrid between two currently supported options:
 * Fully local data: the data files are packaged with the catalog file on the filesystem
 * Fully remote data: the data files are streamed from a remote source (HTTP, S3, GCP, HDFS) on every access

The hybrid case would be to copy the data files from the remote source once (either on first access, or with an explicit "prefetch" command), and then access them locally from then on.  This would both reduce the load on public data servers (by avoiding repeated downloads) and increase loading performance after that first copy.

There are some tricky issues to solve here, but here's one possible approach:

The catalog syntax is extended so that catalog entries can have an optional `cache` section:
``` yaml
sources:
  trips:
    description: taxi trips
    driver: csv
    cache:
        - src: s3://example.com/data/2017-01/
          dest: taxi/2017-01/
          pattern: *.csv
    args:
        urlpath: {{ INTAKE_CACHE }}/taxi/2017-01/*.csv
```
The `cache` section contains a list of dictionaries with `src`, `dest` and `pattern` keys.  Files will be copied from `[src]/[pattern]` to `[INTAKE_CACHE]/[dest]/[pattern]` (where `[INTAKE_CACHE]` is picked to be hidden in the user home directory unless overridden) when the catalog entry is first opened.

Some issues that need to be decided:
* Checksum verification? - Do we want to have an extra option to set SHA256 hashes for downloaded files?  Maybe not yet?
* Cache expiration?  Should we assume that once downloaded, the cache for a catalog entry never needs to be refreshed?  Use a "version number" in the `cache` section (similar in concept to a conda build number) to allow updated catalogs to force the cache to refresh for that entry?
* Control of cache location: We could add a section to the catalog metadata section (#75) to override where cached data is stored.  Otherwise, we can use appdirs to pick a suitable location.
* How to handle dask?  By definition, cached data will be on the client, so we would want to force dask to stream it from the client.  (Not sure how to do that most easily.)
* Intake CLI extensions: At a minimum, we'll need a command to prepopulate the cache for all entries in a given catalog file (or the global catalog space), and a command to clear the cache.

Other issues I might have forgotten?

(Tagging @martindurant and @alimanfoo)

**Comment by alimanfoo** [comment]
Thanks for raising this.

In case it's useful, here's perspective from a particular use case. Use
case is GFF3 and FASTA files which provide gene annotations and reference
genome sequences respectively. I'd like to write a plugin for each, then
I'd like to write a catalog for vectorbase, which hosts these files for a
number of species.

Don't think checksum verification is needed. Can assume files will never
change, i.e., cache never expires. Not sure what you mean about control of
cache location? Don't need to worry about dask, data are generally small
enough that can be read into memory. Might be useful to have a command to
prepopulate cache, but often there will be many more entries in the catalog
than a single user will want to use (because e.g. vectorbase hosts data for
many species, but each user typically works with a single species).

**Comment by seibert** [comment]
OK, its good to know that we can make the first version of this feature pretty minimal and still be useful.

Since Intake will be downloading files on your behalf, I can imagine some people might want to control where those cached files are written.  A reasonable default would be something like `.local/share/intake/cache/` on Linux, but maybe that isn't a good idea in some specific situations.

The only reason I considered pre-populate as a needed feature would be to ensure data is local before going offline (on an airplane, etc), but I agree it isn't essential.

**Comment by martindurant** [comment]
I would use appdirs to decide on a default location. We just started to make a config system, so it would be an obvious option that users may want, to store on a cheap large disc, for instance.

Agree that for this to work in the distributed dask case with direct access, all machines would need to have access to the same cache. We don't want to create such a cluster cache. Non-distributed and client-server don't care about this.

I would suggest that the caching method can also be pluggable, so we can make a simple version cheaply and thereby lay the template for other systems. The extensibility of Intake will be a major selling point, and hopefully drive engagement and a whole ecosystem.

**Comment by seibert** [comment]
The streaming data from the client raises an interesting generic question about Dask, actually.  Is there any concept of "client tasks" that must execute in the client process, even thought it is not a worker.  I assume no (because why add the complexity?), but lazy loading of data from disk on the client in a compute graph is one situation where they would be useful.

**Comment by martindurant** [comment]
I'm not sure I understand the question about dask. You can execute task graphs using a local scheduler, in the same process, but if you want to coordinate tasks between machines, you need the distributed scheduler.

**Comment by alimanfoo** [comment]
Since Intake will be downloading files on your behalf, I can imagine some
people might want to control where those cached files are written. A
reasonable default would be something like .local/share/intake/cache/ on
Linux, but maybe that isn't a good idea in some specific situations.

Yes, would be useful to be able to control the cache location in some cases.
