### ISSUE TITLE
Compare to odo

### ISSUE THREAD

**Issue by rizplate** [ContinuumIO/intake#91]
Can someone compare and contrast intake to blaze/odo?

Do they both have similar goals i.e. ingestion of data? can they both support chunking/streaming?

**Comment by martindurant** [comment]
(odo has not seen significant development in some time)

**Comment by seibert** [comment]
Yeah, I've been wanting to add that history section, since what Intake is trying to be is informed by Blaze (and odo), but not attempting to be a replacement.

Intake is trying to be extremely simple, make data cataloging easy, but also allow going very broad in terms of kinds of data plugins.  Since all of the compute is handled by existing systems (Pandas, Dask, NumPy, etc), the author of a new data source plugin has to do much less work, which will hopefully inspire more of them (and a greater variety of them, see #58).
